/**
 * Automation types for EEN API v3.0
 *
 * @remarks
 * Types for Event Alert Condition Rules, Alert Condition Rules,
 * Alert Action Rules, and Alert Actions.
 *
 * @category Automations
 */

// =============================================================================
// Event Alert Condition Rule Types
// =============================================================================

/**
 * Human validation configuration for event alert condition rules.
 *
 * @category Automations
 */
export interface HumanValidation {
  /** Whether human validation is required */
  required: boolean
  /** Timeout in seconds for validation */
  timeoutSeconds?: number
}

/**
 * Resource filter for event filtering.
 *
 * @category Automations
 */
export interface EventResourceFilter {
  /** Filter by specific account IDs */
  accountIds?: string[]
  /** Filter by specific actor IDs */
  actorIds?: string[]
  /** Filter by actor tags (all must match) */
  actorTags__contains?: string[]
  /** Filter by actor tags (any must match) */
  actorTags__any?: string[]
}

/**
 * Event filter configuration for event alert condition rules.
 *
 * @category Automations
 */
export interface EventFilter {
  /** Event types to include */
  types: string[]
  /** Resource filter configuration */
  resourceFilter?: EventResourceFilter
}

/**
 * Event Alert Condition Rule entity from EEN API v3.0.
 *
 * @remarks
 * Defines conditions under which events trigger alerts. These rules filter
 * incoming events and determine when to generate alerts.
 *
 * @example
 * ```typescript
 * import { listEventAlertConditionRules, type EventAlertConditionRule } from 'een-api-toolkit'
 *
 * const { data, error } = await listEventAlertConditionRules({
 *   enabled: true,
 *   pageSize: 50
 * })
 * if (data) {
 *   data.results.forEach((rule: EventAlertConditionRule) => {
 *     console.log(`Rule: ${rule.name}, Priority: ${rule.priority}`)
 *   })
 * }
 * ```
 *
 * @category Automations
 */
export interface EventAlertConditionRule {
  /** Unique identifier */
  id: string
  /** ISO 8601 timestamp when created */
  createTimestamp: string
  /** ISO 8601 timestamp when last updated */
  updateTimestamp: string
  /** Human-readable name */
  name: string
  /** Priority level (1-10, higher is more important) */
  priority: number
  /** Optional notes about the rule */
  notes?: string
  /** Whether the rule is enabled */
  enabled: boolean
  /** Cooldown period in seconds between alerts */
  cooldownSeconds: number
  /** Human validation configuration */
  humanValidation?: HumanValidation
  /** Event filter configuration */
  eventFilter: EventFilter
  /** Output alert types generated by this rule */
  outputAlertTypes: string[]
}

/**
 * Field values available for filtering event alert condition rules.
 *
 * @category Automations
 */
export interface EventAlertConditionRuleFieldValues {
  /** Available event types */
  eventTypes?: string[]
  /** Available output alert types */
  outputAlertTypes?: string[]
}

// =============================================================================
// Alert Condition Rule Types
// =============================================================================

/**
 * Actor configuration for alert condition rules.
 *
 * @category Automations
 */
export interface AlertConditionRuleActor {
  /** Actor ID */
  id: string
  /** Actor type */
  type: string
  /** Actor account ID */
  accountId?: string
}

/**
 * Action reference in alert condition rules.
 *
 * @category Automations
 */
export interface AlertConditionRuleAction {
  /** Action ID */
  id: string
  /** Action name */
  name?: string
  /** Action type */
  type?: string
}

/**
 * Insights data for alert condition rules.
 *
 * @category Automations
 */
export interface AlertConditionRuleInsights {
  /** Total number of alerts triggered */
  totalAlerts?: number
  /** ISO 8601 timestamp of last triggered alert */
  lastTriggered?: string
  /** Count of alerts by time period */
  alertCounts?: {
    last24Hours?: number
    last7Days?: number
    last30Days?: number
  }
}

/**
 * Alert Condition Rule entity from EEN API v3.0.
 *
 * @remarks
 * Defines rules that process events and create alerts. Each rule specifies
 * input event types and the output alert type to generate.
 *
 * @example
 * ```typescript
 * import { listAlertConditionRules, type AlertConditionRule } from 'een-api-toolkit'
 *
 * const { data, error } = await listAlertConditionRules({
 *   enabled: true,
 *   include: ['actions', 'insights']
 * })
 * ```
 *
 * @category Automations
 */
export interface AlertConditionRule {
  /** Unique identifier */
  id: string
  /** ISO 8601 timestamp when created */
  createTimestamp: string
  /** Rule type identifier */
  type: string
  /** ID of the user who created the rule */
  creatorId: string
  /** Human-readable name */
  name: string
  /** Optional notes about the rule */
  notes?: string
  /** Whether the rule is enabled */
  enabled: boolean
  /** Priority level (1-10) */
  priority: number
  /** Actors (cameras, bridges, etc.) this rule applies to */
  actors: AlertConditionRuleActor[]
  /** Input event types that trigger this rule */
  inputEventTypes: string[]
  /** Output alert type generated by this rule */
  outputAlertType: string
  /** Actions associated with this rule (requires include=actions) */
  actions?: AlertConditionRuleAction[]
  /** Insights about rule performance (requires include=insights) */
  insights?: AlertConditionRuleInsights
}

// =============================================================================
// Alert Action Rule Types
// =============================================================================

/**
 * Alert Action Rule entity from EEN API v3.0.
 *
 * @remarks
 * Connects alerts to actions. When an alert matches the rule's criteria,
 * the associated alert actions are executed.
 *
 * @example
 * ```typescript
 * import { listAlertActionRules, type AlertActionRule } from 'een-api-toolkit'
 *
 * const { data, error } = await listAlertActionRules({
 *   enabled: true,
 *   pageSize: 20
 * })
 * ```
 *
 * @category Automations
 */
export interface AlertActionRule {
  /** Unique identifier */
  id: string
  /** ISO 8601 timestamp when created */
  createTimestamp: string
  /** Human-readable name */
  name: string
  /** Optional notes about the rule */
  notes?: string
  /** Whether the rule is enabled */
  enabled: boolean
  /** Alert types this rule applies to */
  alertTypes: string[]
  /** Actor IDs this rule applies to */
  actorIds: string[]
  /** Actor types this rule applies to */
  actorTypes: string[]
  /** Alert condition rule IDs this rule applies to */
  ruleIds: string[]
  /** Alert action IDs to execute when rule matches */
  alertActionIds: string[]
  /** Minimum priority for alerts (inclusive) */
  priority__gte?: number
  /** Maximum priority for alerts (inclusive) */
  priority__lte?: number
}

// =============================================================================
// Alert Action Types
// =============================================================================

/**
 * Supported alert action types.
 *
 * @category Automations
 */
export type AlertActionType =
  | 'notification'
  | 'sms'
  | 'smtp'
  | 'slack'
  | 'webhook'
  | 'brivo'
  | 'zendesk'
  | 'immix'
  | 'zapier'
  | 'sentinel'
  | 'evalinkTalos'
  | 'outputPort'
  | 'ebus'
  | 'playSpeakerAudioClip'
  | 'zulipPrivate'
  | 'zulipStream'

/**
 * Push notification settings.
 *
 * @category Automations
 */
export interface NotificationSettings {
  /** User IDs to notify */
  userIds: string[]
}

/**
 * SMS notification settings.
 *
 * @category Automations
 */
export interface SmsSettings {
  /** Phone numbers to send SMS to */
  phoneNumbers: string[]
}

/**
 * Email (SMTP) notification settings.
 *
 * @category Automations
 */
export interface SmtpSettings {
  /** Email addresses to send to */
  recipients: string[]
  /** Email subject template */
  subject?: string
  /** Email body template */
  body?: string
}

/**
 * Slack integration settings.
 *
 * @category Automations
 */
export interface SlackSettings {
  /** Slack webhook URL */
  webhookUrl: string
  /** Channel to post to */
  channel?: string
  /** Bot username */
  username?: string
}

/**
 * Webhook settings.
 *
 * @category Automations
 */
export interface WebhookSettings {
  /** Webhook URL */
  url: string
  /** HTTP method */
  method?: 'GET' | 'POST' | 'PUT'
  /** Custom headers */
  headers?: Record<string, string>
}

/**
 * Output port settings for triggering physical outputs.
 *
 * @category Automations
 */
export interface OutputPortSettings {
  /** Device ID */
  deviceId: string
  /** Output port index */
  outputPort: number
  /** Duration in milliseconds */
  durationMs?: number
}

/**
 * Speaker audio clip playback settings.
 *
 * @category Automations
 */
export interface PlaySpeakerAudioClipSettings {
  /** Speaker device ID */
  speakerId: string
  /** Audio clip ID to play */
  audioClipId: string
  /** Volume level (0-100) */
  volume?: number
}

/**
 * Generic settings type for alert actions with unknown types.
 *
 * @category Automations
 */
export type GenericAlertActionSettings = Record<string, unknown>

/**
 * Union type for all alert action settings.
 *
 * @category Automations
 */
export type AlertActionSettings =
  | NotificationSettings
  | SmsSettings
  | SmtpSettings
  | SlackSettings
  | WebhookSettings
  | OutputPortSettings
  | PlaySpeakerAudioClipSettings
  | GenericAlertActionSettings

/**
 * Alert Action entity from EEN API v3.0.
 *
 * @remarks
 * Represents an action that can be executed when an alert is triggered.
 * Actions include notifications, webhooks, integrations, and physical outputs.
 *
 * @example
 * ```typescript
 * import { listAlertActions, type AlertAction } from 'een-api-toolkit'
 *
 * const { data, error } = await listAlertActions({ enabled: true })
 * if (data) {
 *   data.results.forEach((action) => {
 *     console.log(`Action: ${action.name} (${action.type})`)
 *   })
 * }
 * ```
 *
 * @category Automations
 */
export interface AutomationAlertAction {
  /** Unique identifier */
  id: string
  /** ISO 8601 timestamp when created */
  createTimestamp: string
  /** Action type */
  type: AlertActionType
  /** Human-readable name */
  name: string
  /** Optional notes about the action */
  notes?: string
  /** Whether the action is enabled */
  enabled: boolean
  /** Type-specific settings */
  settings: AlertActionSettings
}

// =============================================================================
// Parameter Types
// =============================================================================

/**
 * Parameters for listing event alert condition rules.
 *
 * @example
 * ```typescript
 * const { data } = await listEventAlertConditionRules({
 *   enabled: true,
 *   pageSize: 50,
 *   outputAlertType__in: ['een.motionDetectionAlert.v1']
 * })
 * ```
 *
 * @category Automations
 */
export interface ListEventAlertConditionRulesParams {
  /** Number of results per page */
  pageSize?: number
  /** Token for fetching a specific page */
  pageToken?: string
  /** Filter by enabled status */
  enabled?: boolean
  /** Filter by rule IDs */
  id__in?: string[]
  /** Filter by output alert types */
  outputAlertType__in?: string[]
  /** Filter by minimum priority (inclusive) */
  priority__gte?: number
  /** Filter by maximum priority (inclusive) */
  priority__lte?: number
}

/**
 * Parameters for getting event alert condition rule field values.
 *
 * @category Automations
 */
export interface GetEventAlertConditionRuleFieldValuesParams {
  /** Filter by enabled status */
  enabled?: boolean
}

/**
 * Fields that can be included in alert condition rule responses.
 *
 * @category Automations
 */
export type AlertConditionRuleInclude = 'actions' | 'insights'

/**
 * Parameters for listing alert condition rules.
 *
 * @example
 * ```typescript
 * const { data } = await listAlertConditionRules({
 *   enabled: true,
 *   include: ['actions', 'insights']
 * })
 * ```
 *
 * @category Automations
 */
export interface ListAlertConditionRulesParams {
  /** Number of results per page */
  pageSize?: number
  /** Token for fetching a specific page */
  pageToken?: string
  /** Filter by enabled status */
  enabled?: boolean
  /** Filter by rule IDs */
  id__in?: string[]
  /** Filter by actor IDs */
  actorId__in?: string[]
  /** Filter by input event types */
  inputEventType__in?: string[]
  /** Filter by output alert type */
  outputAlertType?: string
  /** Filter by rule type */
  type?: string
  /** Fields to include in response */
  include?: AlertConditionRuleInclude[]
}

/**
 * Parameters for getting a single alert condition rule.
 *
 * @category Automations
 */
export interface GetAlertConditionRuleParams {
  /** Fields to include in response */
  include?: AlertConditionRuleInclude[]
}

/**
 * Parameters for listing alert action rules.
 *
 * @example
 * ```typescript
 * const { data } = await listAlertActionRules({
 *   enabled: true,
 *   alertType__in: ['een.motionDetectionAlert.v1']
 * })
 * ```
 *
 * @category Automations
 */
export interface ListAlertActionRulesParams {
  /** Number of results per page */
  pageSize?: number
  /** Token for fetching a specific page */
  pageToken?: string
  /** Filter by enabled status */
  enabled?: boolean
  /** Filter by rule IDs */
  id__in?: string[]
  /** Filter by alert types */
  alertType__in?: string[]
  /** Filter by actor IDs */
  actorId__in?: string[]
  /** Filter by alert action IDs */
  alertActionId__in?: string[]
  /** Filter by alert condition rule IDs */
  ruleId__in?: string[]
}

/**
 * Parameters for listing alert actions.
 *
 * @example
 * ```typescript
 * const { data } = await listAlertActions({
 *   enabled: true,
 *   type__in: ['notification', 'webhook']
 * })
 * ```
 *
 * @category Automations
 */
export interface ListAlertActionsParams {
  /** Number of results per page */
  pageSize?: number
  /** Token for fetching a specific page */
  pageToken?: string
  /** Filter by enabled status */
  enabled?: boolean
  /** Filter by action IDs */
  id__in?: string[]
  /** Filter by action types */
  type__in?: AlertActionType[]
}
