/**
 * Feeds API type definitions for the EEN API Toolkit.
 *
 * @remarks
 * The Feeds API allows listing and retrieving information about feeds
 * generated by devices. Feeds represent live or recorded streams in
 * various formats from cameras and other devices.
 *
 * @see {@link https://developer.eagleeyenetworks.com/reference/listfeeds | EEN Feeds API Reference}
 *
 * @module
 * @category Feeds
 */

/**
 * Stream type for a feed.
 *
 * @remarks
 * - `main`: Higher resolution, higher framerate, continuous generation
 * - `preview`: Low resolution, low framerate preview stream
 * - `talkdown`: Two-way communication stream for speakers
 *
 * @category Feeds
 */
export type FeedStreamType = 'main' | 'preview' | 'talkdown'

/**
 * Media type for a feed.
 *
 * @remarks
 * - `video`: Standard video feed
 * - `audio`: Audio-only feed
 * - `image`: Snapshot-based feed
 * - `halfDuplex`: One-way communication
 * - `fullDuplex`: Two-way communication
 *
 * @category Feeds
 */
export type FeedMediaType = 'video' | 'audio' | 'image' | 'halfDuplex' | 'fullDuplex'

/**
 * URL fields that can be included in feed responses.
 *
 * @remarks
 * By default, URL fields are not included in responses. Use the `include`
 * parameter in {@link ListFeedsParams} to request specific URL fields.
 *
 * - `flvUrl`: Flash Video over HTTPS (supports live and playback)
 * - `rtspUrl`: RTSP protocol stream
 * - `rtspsUrl`: RTSP over TLS (encrypted)
 * - `localRtspUrl`: RTSP directly to bridge (not cloud)
 * - `hlsUrl`: HTTP Live Streaming over HTTPS
 * - `multipartUrl`: Proprietary protocol for raw frames
 * - `webRtcUrl`: WebRTC for push-to-talk connections
 * - `audioPushHttpsUrl`: Audio push URL for speakers
 *
 * @category Feeds
 */
export type FeedIncludeOption =
  | 'flvUrl'
  | 'rtspUrl'
  | 'rtspsUrl'
  | 'localRtspUrl'
  | 'hlsUrl'
  | 'multipartUrl'
  | 'webRtcUrl'
  | 'audioPushHttpsUrl'

/**
 * Union type of URL field names on the Feed interface.
 *
 * @remarks
 * This type represents only the URL fields of a Feed, not other properties
 * like `id`, `type`, or `deviceId`. Use this for type-safe URL field operations.
 *
 * @category Feeds
 */
export type FeedUrlField = FeedIncludeOption

/**
 * A feed representing a stream from a device.
 *
 * @remarks
 * Feeds are associated with devices (cameras, speakers) and provide
 * streaming URLs in various formats. A single device can have multiple
 * feeds (main, preview, talkdown).
 *
 * URL fields are only populated if requested via the `include` parameter.
 *
 * @example
 * ```typescript
 * const feed: Feed = {
 *   id: '10058b7a-main',
 *   type: 'main',
 *   deviceId: '10058b7a',
 *   mediaType: 'video',
 *   hlsUrl: 'https://...',
 *   flvUrl: 'https://...'
 * }
 * ```
 *
 * @category Feeds
 */
export interface Feed {
  /** Unique feed identifier (typically deviceId-type format) */
  id: string

  /** Stream type of the feed */
  type: FeedStreamType

  /** ID of the device generating this feed */
  deviceId: string

  /** Media type of the feed content */
  mediaType: FeedMediaType

  /** Flash Video URL (if requested via include) */
  flvUrl?: string | null

  /** RTSP URL (if requested via include) */
  rtspUrl?: string | null

  /** RTSP over TLS URL (if requested via include) */
  rtspsUrl?: string | null

  /** Local RTSP URL to bridge (if requested via include) */
  localRtspUrl?: string | null

  /** HLS URL (if requested via include) */
  hlsUrl?: string | null

  /** Multipart URL for raw frames (if requested via include) */
  multipartUrl?: string | null

  /** WebRTC URL (if requested via include) */
  webRtcUrl?: string | null

  /** Audio push URL for speakers (if requested via include) */
  audioPushHttpsUrl?: string | null
}

/**
 * Parameters for listing feeds.
 *
 * @remarks
 * Use these parameters to filter and paginate feed results.
 * The `include` parameter controls which URL fields are returned.
 *
 * @example
 * ```typescript
 * // Get all feeds for a specific camera with HLS and multipart URLs
 * const params: ListFeedsParams = {
 *   deviceId: '10058b7a',
 *   include: ['hlsUrl', 'multipartUrl']
 * }
 *
 * // Get preview feeds for multiple cameras
 * const params: ListFeedsParams = {
 *   deviceId__in: ['10058b7a', '10058b7b'],
 *   type: 'preview'
 * }
 * ```
 *
 * @category Feeds
 */
export interface ListFeedsParams {
  /** Filter by single device ID */
  deviceId?: string

  /** Filter by multiple device IDs */
  deviceId__in?: string[]

  /** Filter by stream type */
  type?: FeedStreamType

  /** URL fields to include in response */
  include?: FeedIncludeOption[]

  /** Number of results per page */
  pageSize?: number

  /** Pagination cursor from previous response */
  pageToken?: string

  /** AbortSignal for cancelling the request */
  signal?: AbortSignal
}

/**
 * Result from listing feeds.
 *
 * @remarks
 * Contains the paginated list of feeds and pagination metadata.
 * Use `nextPageToken` with subsequent requests to fetch more results.
 *
 * @example
 * ```typescript
 * const result: ListFeedsResult = {
 *   results: [
 *     { id: '10058b7a-main', type: 'main', deviceId: '10058b7a', mediaType: 'video' },
 *     { id: '10058b7a-preview', type: 'preview', deviceId: '10058b7a', mediaType: 'video' }
 *   ],
 *   nextPageToken: 'abc123',
 *   totalSize: 50
 * }
 * ```
 *
 * @category Feeds
 */
export interface ListFeedsResult {
  /** Array of feed objects */
  results: Feed[]

  /** Token for fetching next page (undefined if no more results) */
  nextPageToken?: string

  /** Total number of feeds available (may not always be provided) */
  totalSize?: number
}
